version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sentido
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  app:
    build: .
    volumes:
      - ./templates:/app/templates
      - ./output:/app/output
      - ./entrypoint.sh:/app/entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:12345678@db:5432/sentido
      - TEMPLATE_DIR=/app/templates
      - OUTPUT_DIR=/app/output
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "/app/entrypoint.sh"]
    restart: always

volumes:
  postgres_data:
